{{- if not .Values.secrets.existingSecrets.worker }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tali.secretName" (dict "root" . "component" "worker") }}
  labels:
    {{- include "tali.componentLabels" (dict "root" . "component" "control-worker") | nindent 4 }}
  annotations:
    {{- include "tali.resourceAnnotations" (dict "root" . "wave" "foundation") | nindent 4 }}
type: Opaque
stringData:
  worker.toml: |
{{ include "tali.workerConfig" . | indent 4 }}
{{- end }}
