{{- if and .Values.openshift.enabled .Values.openshift.anyuidScc.createRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tali.componentName" (dict "root" . "component" "anyuid") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tali.labels" . | nindent 4 }}
  annotations:
    {{- include "tali.resourceAnnotations" (dict "root" . "wave" "prerequisites") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: {{ include "tali.runtimeServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "tali.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.control.worker.enabled }}
  - kind: ServiceAccount
    name: {{ include "tali.controlWorkerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
