/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdCostRouteImport } from './routes/$projectId/cost'
import { Route as ProjectIdHelpRouteImport } from './routes/$projectId/help'
import { Route as ProjectIdMcpServersRouteImport } from './routes/$projectId/mcp-servers'
import { Route as ProjectIdNotificationsRouteImport } from './routes/$projectId/notifications'
import { Route as ProjectIdRuntimeRouteImport } from './routes/$projectId/runtime'
import { Route as ProjectIdRuntimePoliciesRouteImport } from './routes/$projectId/runtime-policies'
import { Route as ProjectIdSkillsRouteImport } from './routes/$projectId/skills'
import { Route as ProjectIdTracesRouteImport } from './routes/$projectId/traces'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments/$departmentId'
import { Route as PlatformSettingsRouteImport } from './routes/platform/settings'
import { Route as ProjectIdAccessPoliciesIndexRouteImport } from './routes/$projectId/access-policies/index'
import { Route as ProjectIdAccessPoliciesPolicyIdRouteImport } from './routes/$projectId/access-policies/$policyId'
import { Route as ProjectIdAgentGardenIndexRouteImport } from './routes/$projectId/agent-garden/index'
import { Route as ProjectIdAgentGardenAgentIdRouteImport } from './routes/$projectId/agent-garden/$agentId'
import { Route as ProjectIdAuditLogsIndexRouteImport } from './routes/$projectId/audit-logs/index'
import { Route as ProjectIdInstancesIndexRouteImport } from './routes/$projectId/instances/index'
import { Route as ProjectIdInstancesInstanceIdRouteImport } from './routes/$projectId/instances/$instanceId'
import { Route as ProjectIdMemoryIndexRouteImport } from './routes/$projectId/memory/index'
import { Route as ProjectIdMemoryMemoryIdRouteImport } from './routes/$projectId/memory/$memoryId'
import { Route as ProjectIdRequestsIndexRouteImport } from './routes/$projectId/requests/index'
import { Route as ProjectIdRequestsNewRouteImport } from './routes/$projectId/requests/new'
import { Route as ProjectIdSettingIndexRouteImport } from './routes/$projectId/setting/index'
import { Route as ProjectIdVectorDatabasesIndexRouteImport } from './routes/$projectId/vector-databases/index'
import { Route as ProjectIdVectorDatabasesDatabaseIdRouteImport } from './routes/$projectId/vector-databases/$databaseId'
import { Route as ProjectIdSettingModelRoutingsRoutingIdRouteImport } from './routes/$projectId/setting/model-routings/$routingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdCostRoute = ProjectIdCostRouteImport.update({
  id: '/$projectId/cost',
  path: '/$projectId/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdHelpRoute = ProjectIdHelpRouteImport.update({
  id: '/$projectId/help',
  path: '/$projectId/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMcpServersRoute = ProjectIdMcpServersRouteImport.update({
  id: '/$projectId/mcp-servers',
  path: '/$projectId/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdNotificationsRoute = ProjectIdNotificationsRouteImport.update({
  id: '/$projectId/notifications',
  path: '/$projectId/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimeRoute = ProjectIdRuntimeRouteImport.update({
  id: '/$projectId/runtime',
  path: '/$projectId/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRuntimePoliciesRoute =
  ProjectIdRuntimePoliciesRouteImport.update({
    id: '/$projectId/runtime-policies',
    path: '/$projectId/runtime-policies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSkillsRoute = ProjectIdSkillsRouteImport.update({
  id: '/$projectId/skills',
  path: '/$projectId/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdTracesRoute = ProjectIdTracesRouteImport.update({
  id: '/$projectId/traces',
  path: '/$projectId/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/departments/$departmentId',
  path: '/departments/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/platform/settings',
  path: '/platform/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdAccessPoliciesIndexRoute =
  ProjectIdAccessPoliciesIndexRouteImport.update({
    id: '/$projectId/access-policies/',
    path: '/$projectId/access-policies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAccessPoliciesPolicyIdRoute =
  ProjectIdAccessPoliciesPolicyIdRouteImport.update({
    id: '/$projectId/access-policies/$policyId',
    path: '/$projectId/access-policies/$policyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenIndexRoute =
  ProjectIdAgentGardenIndexRouteImport.update({
    id: '/$projectId/agent-garden/',
    path: '/$projectId/agent-garden/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAgentGardenAgentIdRoute =
  ProjectIdAgentGardenAgentIdRouteImport.update({
    id: '/$projectId/agent-garden/$agentId',
    path: '/$projectId/agent-garden/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdAuditLogsIndexRoute = ProjectIdAuditLogsIndexRouteImport.update({
  id: '/$projectId/audit-logs/',
  path: '/$projectId/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesIndexRoute = ProjectIdInstancesIndexRouteImport.update({
  id: '/$projectId/instances/',
  path: '/$projectId/instances/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdInstancesInstanceIdRoute =
  ProjectIdInstancesInstanceIdRouteImport.update({
    id: '/$projectId/instances/$instanceId',
    path: '/$projectId/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdMemoryIndexRoute = ProjectIdMemoryIndexRouteImport.update({
  id: '/$projectId/memory/',
  path: '/$projectId/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdMemoryMemoryIdRoute = ProjectIdMemoryMemoryIdRouteImport.update({
  id: '/$projectId/memory/$memoryId',
  path: '/$projectId/memory/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRequestsIndexRoute = ProjectIdRequestsIndexRouteImport.update({
  id: '/$projectId/requests/',
  path: '/$projectId/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRequestsNewRoute = ProjectIdRequestsNewRouteImport.update({
  id: '/$projectId/requests/new',
  path: '/$projectId/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdSettingIndexRoute = ProjectIdSettingIndexRouteImport.update({
  id: '/$projectId/setting/',
  path: '/$projectId/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdVectorDatabasesIndexRoute =
  ProjectIdVectorDatabasesIndexRouteImport.update({
    id: '/$projectId/vector-databases/',
    path: '/$projectId/vector-databases/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdVectorDatabasesDatabaseIdRoute =
  ProjectIdVectorDatabasesDatabaseIdRouteImport.update({
    id: '/$projectId/vector-databases/$databaseId',
    path: '/$projectId/vector-databases/$databaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectIdSettingModelRoutingsRoutingIdRoute =
  ProjectIdSettingModelRoutingsRoutingIdRouteImport.update({
    id: '/$projectId/setting/model-routings/$routingId',
    path: '/$projectId/setting/model-routings/$routingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/help': typeof ProjectIdHelpRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/notifications': typeof ProjectIdNotificationsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/memory/$memoryId': typeof ProjectIdMemoryMemoryIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/vector-databases/$databaseId': typeof ProjectIdVectorDatabasesDatabaseIdRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/memory/': typeof ProjectIdMemoryIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/vector-databases/': typeof ProjectIdVectorDatabasesIndexRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/help': typeof ProjectIdHelpRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/notifications': typeof ProjectIdNotificationsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/memory/$memoryId': typeof ProjectIdMemoryMemoryIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/vector-databases/$databaseId': typeof ProjectIdVectorDatabasesDatabaseIdRoute
  '/$projectId/access-policies': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances': typeof ProjectIdInstancesIndexRoute
  '/$projectId/memory': typeof ProjectIdMemoryIndexRoute
  '/$projectId/requests': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting': typeof ProjectIdSettingIndexRoute
  '/$projectId/vector-databases': typeof ProjectIdVectorDatabasesIndexRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/$projectId/cost': typeof ProjectIdCostRoute
  '/$projectId/help': typeof ProjectIdHelpRoute
  '/$projectId/mcp-servers': typeof ProjectIdMcpServersRoute
  '/$projectId/notifications': typeof ProjectIdNotificationsRoute
  '/$projectId/runtime': typeof ProjectIdRuntimeRoute
  '/$projectId/runtime-policies': typeof ProjectIdRuntimePoliciesRoute
  '/$projectId/skills': typeof ProjectIdSkillsRoute
  '/$projectId/traces': typeof ProjectIdTracesRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/access-policies/$policyId': typeof ProjectIdAccessPoliciesPolicyIdRoute
  '/$projectId/agent-garden/$agentId': typeof ProjectIdAgentGardenAgentIdRoute
  '/$projectId/instances/$instanceId': typeof ProjectIdInstancesInstanceIdRoute
  '/$projectId/memory/$memoryId': typeof ProjectIdMemoryMemoryIdRoute
  '/$projectId/requests/new': typeof ProjectIdRequestsNewRoute
  '/$projectId/vector-databases/$databaseId': typeof ProjectIdVectorDatabasesDatabaseIdRoute
  '/$projectId/access-policies/': typeof ProjectIdAccessPoliciesIndexRoute
  '/$projectId/agent-garden/': typeof ProjectIdAgentGardenIndexRoute
  '/$projectId/audit-logs/': typeof ProjectIdAuditLogsIndexRoute
  '/$projectId/instances/': typeof ProjectIdInstancesIndexRoute
  '/$projectId/memory/': typeof ProjectIdMemoryIndexRoute
  '/$projectId/requests/': typeof ProjectIdRequestsIndexRoute
  '/$projectId/setting/': typeof ProjectIdSettingIndexRoute
  '/$projectId/vector-databases/': typeof ProjectIdVectorDatabasesIndexRoute
  '/$projectId/setting/model-routings/$routingId': typeof ProjectIdSettingModelRoutingsRoutingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/account'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/help'
    | '/$projectId/mcp-servers'
    | '/$projectId/notifications'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/departments/$departmentId'
    | '/platform/settings'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/memory/$memoryId'
    | '/$projectId/requests/new'
    | '/$projectId/vector-databases/$databaseId'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/instances/'
    | '/$projectId/memory/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/vector-databases/'
    | '/$projectId/setting/model-routings/$routingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/account'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/help'
    | '/$projectId/mcp-servers'
    | '/$projectId/notifications'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/departments/$departmentId'
    | '/platform/settings'
    | '/$projectId'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/memory/$memoryId'
    | '/$projectId/requests/new'
    | '/$projectId/vector-databases/$databaseId'
    | '/$projectId/access-policies'
    | '/$projectId/agent-garden'
    | '/$projectId/audit-logs'
    | '/$projectId/instances'
    | '/$projectId/memory'
    | '/$projectId/requests'
    | '/$projectId/setting'
    | '/$projectId/vector-databases'
    | '/$projectId/setting/model-routings/$routingId'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/account'
    | '/login'
    | '/$projectId/cost'
    | '/$projectId/help'
    | '/$projectId/mcp-servers'
    | '/$projectId/notifications'
    | '/$projectId/runtime'
    | '/$projectId/runtime-policies'
    | '/$projectId/skills'
    | '/$projectId/traces'
    | '/departments/$departmentId'
    | '/platform/settings'
    | '/$projectId/'
    | '/$projectId/access-policies/$policyId'
    | '/$projectId/agent-garden/$agentId'
    | '/$projectId/instances/$instanceId'
    | '/$projectId/memory/$memoryId'
    | '/$projectId/requests/new'
    | '/$projectId/vector-databases/$databaseId'
    | '/$projectId/access-policies/'
    | '/$projectId/agent-garden/'
    | '/$projectId/audit-logs/'
    | '/$projectId/instances/'
    | '/$projectId/memory/'
    | '/$projectId/requests/'
    | '/$projectId/setting/'
    | '/$projectId/vector-databases/'
    | '/$projectId/setting/model-routings/$routingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  ProjectIdCostRoute: typeof ProjectIdCostRoute
  ProjectIdHelpRoute: typeof ProjectIdHelpRoute
  ProjectIdMcpServersRoute: typeof ProjectIdMcpServersRoute
  ProjectIdNotificationsRoute: typeof ProjectIdNotificationsRoute
  ProjectIdRuntimeRoute: typeof ProjectIdRuntimeRoute
  ProjectIdRuntimePoliciesRoute: typeof ProjectIdRuntimePoliciesRoute
  ProjectIdSkillsRoute: typeof ProjectIdSkillsRoute
  ProjectIdTracesRoute: typeof ProjectIdTracesRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdAccessPoliciesPolicyIdRoute: typeof ProjectIdAccessPoliciesPolicyIdRoute
  ProjectIdAgentGardenAgentIdRoute: typeof ProjectIdAgentGardenAgentIdRoute
  ProjectIdInstancesInstanceIdRoute: typeof ProjectIdInstancesInstanceIdRoute
  ProjectIdMemoryMemoryIdRoute: typeof ProjectIdMemoryMemoryIdRoute
  ProjectIdRequestsNewRoute: typeof ProjectIdRequestsNewRoute
  ProjectIdVectorDatabasesDatabaseIdRoute: typeof ProjectIdVectorDatabasesDatabaseIdRoute
  ProjectIdAccessPoliciesIndexRoute: typeof ProjectIdAccessPoliciesIndexRoute
  ProjectIdAgentGardenIndexRoute: typeof ProjectIdAgentGardenIndexRoute
  ProjectIdAuditLogsIndexRoute: typeof ProjectIdAuditLogsIndexRoute
  ProjectIdInstancesIndexRoute: typeof ProjectIdInstancesIndexRoute
  ProjectIdMemoryIndexRoute: typeof ProjectIdMemoryIndexRoute
  ProjectIdRequestsIndexRoute: typeof ProjectIdRequestsIndexRoute
  ProjectIdSettingIndexRoute: typeof ProjectIdSettingIndexRoute
  ProjectIdVectorDatabasesIndexRoute: typeof ProjectIdVectorDatabasesIndexRoute
  ProjectIdSettingModelRoutingsRoutingIdRoute: typeof ProjectIdSettingModelRoutingsRoutingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/cost': {
      id: '/$projectId/cost'
      path: '/$projectId/cost'
      fullPath: '/$projectId/cost'
      preLoaderRoute: typeof ProjectIdCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/help': {
      id: '/$projectId/help'
      path: '/$projectId/help'
      fullPath: '/$projectId/help'
      preLoaderRoute: typeof ProjectIdHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/mcp-servers': {
      id: '/$projectId/mcp-servers'
      path: '/$projectId/mcp-servers'
      fullPath: '/$projectId/mcp-servers'
      preLoaderRoute: typeof ProjectIdMcpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/notifications': {
      id: '/$projectId/notifications'
      path: '/$projectId/notifications'
      fullPath: '/$projectId/notifications'
      preLoaderRoute: typeof ProjectIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime': {
      id: '/$projectId/runtime'
      path: '/$projectId/runtime'
      fullPath: '/$projectId/runtime'
      preLoaderRoute: typeof ProjectIdRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/runtime-policies': {
      id: '/$projectId/runtime-policies'
      path: '/$projectId/runtime-policies'
      fullPath: '/$projectId/runtime-policies'
      preLoaderRoute: typeof ProjectIdRuntimePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/skills': {
      id: '/$projectId/skills'
      path: '/$projectId/skills'
      fullPath: '/$projectId/skills'
      preLoaderRoute: typeof ProjectIdSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/traces': {
      id: '/$projectId/traces'
      path: '/$projectId/traces'
      fullPath: '/$projectId/traces'
      preLoaderRoute: typeof ProjectIdTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$departmentId': {
      id: '/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/platform/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/': {
      id: '/$projectId/access-policies/'
      path: '/$projectId/access-policies'
      fullPath: '/$projectId/access-policies/'
      preLoaderRoute: typeof ProjectIdAccessPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/access-policies/$policyId': {
      id: '/$projectId/access-policies/$policyId'
      path: '/$projectId/access-policies/$policyId'
      fullPath: '/$projectId/access-policies/$policyId'
      preLoaderRoute: typeof ProjectIdAccessPoliciesPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/': {
      id: '/$projectId/agent-garden/'
      path: '/$projectId/agent-garden'
      fullPath: '/$projectId/agent-garden/'
      preLoaderRoute: typeof ProjectIdAgentGardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/agent-garden/$agentId': {
      id: '/$projectId/agent-garden/$agentId'
      path: '/$projectId/agent-garden/$agentId'
      fullPath: '/$projectId/agent-garden/$agentId'
      preLoaderRoute: typeof ProjectIdAgentGardenAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/audit-logs/': {
      id: '/$projectId/audit-logs/'
      path: '/$projectId/audit-logs'
      fullPath: '/$projectId/audit-logs/'
      preLoaderRoute: typeof ProjectIdAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/': {
      id: '/$projectId/instances/'
      path: '/$projectId/instances'
      fullPath: '/$projectId/instances/'
      preLoaderRoute: typeof ProjectIdInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/instances/$instanceId': {
      id: '/$projectId/instances/$instanceId'
      path: '/$projectId/instances/$instanceId'
      fullPath: '/$projectId/instances/$instanceId'
      preLoaderRoute: typeof ProjectIdInstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/memory/': {
      id: '/$projectId/memory/'
      path: '/$projectId/memory'
      fullPath: '/$projectId/memory/'
      preLoaderRoute: typeof ProjectIdMemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/memory/$memoryId': {
      id: '/$projectId/memory/$memoryId'
      path: '/$projectId/memory/$memoryId'
      fullPath: '/$projectId/memory/$memoryId'
      preLoaderRoute: typeof ProjectIdMemoryMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/': {
      id: '/$projectId/requests/'
      path: '/$projectId/requests'
      fullPath: '/$projectId/requests/'
      preLoaderRoute: typeof ProjectIdRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/requests/new': {
      id: '/$projectId/requests/new'
      path: '/$projectId/requests/new'
      fullPath: '/$projectId/requests/new'
      preLoaderRoute: typeof ProjectIdRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/': {
      id: '/$projectId/setting/'
      path: '/$projectId/setting'
      fullPath: '/$projectId/setting/'
      preLoaderRoute: typeof ProjectIdSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/vector-databases/': {
      id: '/$projectId/vector-databases/'
      path: '/$projectId/vector-databases'
      fullPath: '/$projectId/vector-databases/'
      preLoaderRoute: typeof ProjectIdVectorDatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/vector-databases/$databaseId': {
      id: '/$projectId/vector-databases/$databaseId'
      path: '/$projectId/vector-databases/$databaseId'
      fullPath: '/$projectId/vector-databases/$databaseId'
      preLoaderRoute: typeof ProjectIdVectorDatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/setting/model-routings/$routingId': {
      id: '/$projectId/setting/model-routings/$routingId'
      path: '/$projectId/setting/model-routings/$routingId'
      fullPath: '/$projectId/setting/model-routings/$routingId'
      preLoaderRoute: typeof ProjectIdSettingModelRoutingsRoutingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  ProjectIdCostRoute: ProjectIdCostRoute,
  ProjectIdHelpRoute: ProjectIdHelpRoute,
  ProjectIdMcpServersRoute: ProjectIdMcpServersRoute,
  ProjectIdNotificationsRoute: ProjectIdNotificationsRoute,
  ProjectIdRuntimeRoute: ProjectIdRuntimeRoute,
  ProjectIdRuntimePoliciesRoute: ProjectIdRuntimePoliciesRoute,
  ProjectIdSkillsRoute: ProjectIdSkillsRoute,
  ProjectIdTracesRoute: ProjectIdTracesRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdAccessPoliciesPolicyIdRoute: ProjectIdAccessPoliciesPolicyIdRoute,
  ProjectIdAgentGardenAgentIdRoute: ProjectIdAgentGardenAgentIdRoute,
  ProjectIdInstancesInstanceIdRoute: ProjectIdInstancesInstanceIdRoute,
  ProjectIdMemoryMemoryIdRoute: ProjectIdMemoryMemoryIdRoute,
  ProjectIdRequestsNewRoute: ProjectIdRequestsNewRoute,
  ProjectIdVectorDatabasesDatabaseIdRoute:
    ProjectIdVectorDatabasesDatabaseIdRoute,
  ProjectIdAccessPoliciesIndexRoute: ProjectIdAccessPoliciesIndexRoute,
  ProjectIdAgentGardenIndexRoute: ProjectIdAgentGardenIndexRoute,
  ProjectIdAuditLogsIndexRoute: ProjectIdAuditLogsIndexRoute,
  ProjectIdInstancesIndexRoute: ProjectIdInstancesIndexRoute,
  ProjectIdMemoryIndexRoute: ProjectIdMemoryIndexRoute,
  ProjectIdRequestsIndexRoute: ProjectIdRequestsIndexRoute,
  ProjectIdSettingIndexRoute: ProjectIdSettingIndexRoute,
  ProjectIdVectorDatabasesIndexRoute: ProjectIdVectorDatabasesIndexRoute,
  ProjectIdSettingModelRoutingsRoutingIdRoute:
    ProjectIdSettingModelRoutingsRoutingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
